### ISSUE TITLE
Bug for 0,5,10,15...

### ISSUE THREAD

**Issue by zeoc** [arnapou/jqcron#23]
In the php cronToArray() function the code do notwork in some case like 
0,5,10,15
the first loop find de 0 : OK then change the 0 to '' so the next loop have 5,11,15
we loose the 0 of 10 !...

as the jquery plugin generate these kind of "cron" string I think we have to fix that...
I'll my hand but if you can fix here it'll be better.
thanks

**Comment by arnapou** [comment]
Can you provide me a buggy php snippet of code ? thank you.

**Comment by zeoc** [comment]
$cron = *new *Cron("0,5,10,15 * * * *");

echo $cron->getText();





    Stéphane COEZ
     04 22 14 00 71
     06 78 29 28 34



2015-03-12 14:46 GMT+01:00 Arnaud Buathier <notifications@github.com>:

**Comment by zeoc** [comment]
$cron = *new *Cron("0,5,10,15 * * * *");

echo $cron->getText("en");


    Stéphane COEZ
     04 22 14 00 71
     06 78 29 28 34



2015-03-12 14:51 GMT+01:00 Stéphane COEZ <stephane@coez.net>:

**Comment by arnapou** [comment]
Corrected, I don't know why I used str_replace instead of substr ... well too few people use the php class I guess. Let me know if you have any problem nwo.

**Comment by zeoc** [comment]
Thanks for this very fast update.
it works better...



    Stéphane COEZ




2015-03-12 15:59 GMT+01:00 Arnaud Buathier <notifications@github.com>:
