### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by stoiev** [arnapou/jqcron#28]
Isn't this project stable enough for a release version?

It will be wonderful for dependent projects.

**Comment by arnapou** [comment]
> Isn't this project stable enough for a release version?

Probably, but I made this project for my own usage, but free to be used. I never planned to manage it as a real project with a roadmap development ...

I have not the time to manage versions, stable/unstable, etc ... I never managed that (need skills to do it properly). I don't know if it is possible through GitHub to grant version control management to someone else. If a huge contibutor ask for that one day, and if doable, he will manage that. But probably never me.

Sorry, but I hope you will understand.

**Comment by stoiev** [comment]
Shure Arnaud, thanks for this project (Y)
