### ISSUE TITLE
register in bower registry

### ISSUE THREAD

**Issue by Rebyrg** [arnapou/jqcron#29]
Can you register jqcron in bower registry?
I use bower to manage my project dependencies. Now I have in my bower.json:

    "jqcron-master": "https://github.com/arnapou/jqcron"

I would like to use jqcron like other my dependencies:

    "jqcron-master": "latest"

But jgcron must be registered in bower registry.

**Comment by alexcheng1982** [comment]
Add following line to your `bower.json` file.
~~~~~
"jqcron": "arnapou/jqcron#master"
~~~~~

**Comment by arnapou** [comment]
Sorry but I don't use bower, I don't know how it works. The bower file exists because somebody made a pull request for that. Do the same, please.
