### ISSUE TITLE
Sometime popup is not opening  after click on second drop down 

### ISSUE THREAD

**Issue by amitonline3** [arnapou/jqcron#30]
First of all thanks for jqCron . I am facing one issue.  Sometime when we click  on second drop down which comes after selecting  value from first " Every" drop down nothing gets open like div for selecting calendar component second drop down just get close down. After page refresh everything work fine.  This is happening very rarely. Any idea to resolve this?

**Comment by arnapou** [comment]
I never saw that bug. In order to be able to correct it, I need to have a way to reproduce it. If you can manage to make a fiddle or something like that I can use to reproduce it, I will look at that.

**Comment by amitonline3** [comment]
Thanks!!!

Looks like issue with my code for conversion to support Quartz format.  Is it possible to change the 'dayOfWeek' to Sunday in place of Monday in jqcron as in Quartz format  '1' value in 'dayOfWeek' means sunday but in jqcron '1' indicate Monday

Quartz cron format 
 http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger 
http://www.cronmaker.com/ to check Quartz cron format

I have written this function to convert jqCron to QuatzCron . looks like its working fine except dayOfWeek issue. 

function convertToQuartz(val) {
        var tmpVal = val;
        var cronDayOfMonth,
                cronDayOfWeek;

       var origCron = tmpVal.split(' ');

        var cronDayOfMonth = origCron[2];
        var cronDayOfWeek = origCron[4];

        //adding 0 to support quartz cron fromat
        origCron.unshift(0);
        var tmpQuarthFormat;

        if (cronDayOfMonth === "*") {
            tmpQuarthFormat = origCron.slice();
            tmpQuarthFormat[3] = '?';
        } else if (cronDayOfWeek === "*" && cronDayOfMonth === '*') {
            tmpQuarthFormat = origCron.slice();
            tmpQuarthFormat[5] = '?';
        }
        else if (cronDayOfWeek === "*") {
            tmpQuarthFormat = origCron.slice();
            tmpQuarthFormat[5] = '?';
        }
        else {
            tmpQuarthFormat = origCron.slice();
        }
        tmpQuarthFormat.join(' ');
        return tmpQuarthFormat.join(' ');
    }

**Comment by arnapou** [comment]
I apologize, I never took the time to track this precisely.
I guess it is useless now to try to fix that.
This tool (jqCron) is an old development from me (6 years old), and I can't spend time on it.
If you need it today, I guess you probably has better ways to achieve the same goal through popular frontends (angular, react, ...).
