### ISSUE TITLE
How to create cron for Last Day of Month?

### ISSUE THREAD

**Issue by mdadilsiddiqui** [arnapou/jqcron#31]
There is no option to create cron for Last Day of Month.

Can you please add feature to create cron for Last Day of Month?

**Comment by arnapou** [comment]
Hello. I am sorry, but this feature is not supported by standard cron syntax (cf. https://en.wikipedia.org/wiki/Cron ). 
jqCron cannot manage it. The better I can imagine is to have 3 separate crons for months with 31 days, months with 30 days, and february.

**Comment by mdadilsiddiqui** [comment]
Thank you
