### ISSUE TITLE
var_dump to string

### ISSUE THREAD

**Issue by emresaracoglu** [arnapou/jqcron#37]
Hi,

How I can convert var_dump to string?

```
 $cron = new Cron('10-30/5 12 * * *');
 var_dump($cron->getText('en'));
```
Result:

`string(30) "Every day at 12:10,15,20,25,30"`

How I can delete this text "**string(30)**" ?

**Comment by arnapou** [comment]
Check http://php.net/ and read the documentation. This is a trivial question for a php developper.
