### ISSUE TITLE
Add Russian Language

### ISSUE THREAD

**Issue by mdimai666** [arnapou/jqcron#39]
**file: src\jqCron.ru.js**

`jqCronDefaultSettings.texts.ru = {
	empty: 'каждые',
	empty_minutes: 'каждые',
	empty_time_hours: 'каждые часов',
	empty_time_minutes: 'каждые минут',
	empty_day_of_week: 'день недели',
	empty_day_of_month: 'каждый день месяца',
	empty_month: 'каждый месяц',
	name_minute: 'минута',
	name_hour: 'час',
	name_day: 'день',
	name_week: 'неделю',
	name_month: 'месяц',
	name_year: 'год',
	text_period: 'Каждый <b />',
	text_mins: ' в <b /> минут',
	text_time: ' в <b />:<b />',
	text_dow: ' в <b />',
	text_month: ' числа, <b />',
	text_dom: ' в <b />',
	error1: 'Тег %s не поддерживается !',
	error2: 'Количество элементов не верно',
	error3: 'jquery_element следует установить в настройки jqCron',
	error4: 'Нераспознанное выражение',
	weekdays: ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'],
	months: ['январь', 'февраль', 'март ', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь']
};`

**Comment by arnapou** [comment]
File added. Thank you for your contribution
