### ISSUE TITLE
Using into containers with overflow: hidden

### ISSUE THREAD

**Issue by MartinEmbers** [arnapou/jqcron#45]
Please investigate possibility of introduction containers with overflow: hidden support
![image](https://user-images.githubusercontent.com/15820133/48054996-9b947100-e1bf-11e8-9ddd-4ab34443c9ae.png)

You can use system dropdowns instead of ul lists or you can move ul lists to the end of body element

**Comment by arnapou** [comment]
There is no simple solution. The css is light and will stay like that. Moving ul at the end of the body will bring a truck of problems when resizing windows ... etc ... Sorry.
